# Generated by Django 3.2.12 on 2022-02-23 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0002_auto_20220222_1904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='imagePath',
            field=models.ImageField(upload_to=''),
        ),
    ]
